export const episodeData = [
  {
    title: "Sonnie's Edge",
    season: '1',
    episodeNumber: 1,
    secondaryDetails: {
      directed_By: 'Dave Wilson',
      adapted_Script_By: 'Philip Gelatt',
      based_On_The_Story_By: 'Peter F. Hamilton',
      animation_Studio: 'Blur Studio',
      release_Date: '15/03/19',
      duration: 17,
    },
    description:
      "In the underground world of 'beastie' fights, Sonnie is unbeatable -- as long as she keeps her edge.",
    icons: ['heart', 'x_2', 'snake'],
    backgroundImg: 'Sonnies_Edge',
    rating: 8.3,
  },
  {
    title: 'Three Robots',
    season: '1',
    episodeNumber: 2,
    secondaryDetails: {
      directed_By: 'Victor Maldonado & Alfredo Torres',
      adapted_Script_By: 'Philip Gelatt',
      based_On_The_Story_By: 'John Scalzi',
      animation_Studio: 'Blow Studio',
      release_Date: '15/03/19',
      duration: 12,
    },
    description:
      'Long after the fall of humanity, three robots embark on a sightseeing tour of a post-apocalyptic city.',
    icons: ['one_eyed_skull', 'cycloptic_pyramid', 'dripping_hamburger'],
    backgroundImg: 'Three_Robots',
    rating: 8.0,
  },
  {
    title: 'The Witness',
    season: '1',
    episodeNumber: 3,
    secondaryDetails: {
      directed_By: 'Alberto Mielgo',
      adapted_Script_By: 'ALbert Mielgo',
      based_On_The_Story_By: 'N/A',
      animation_Studio: 'Pinkman TV',
      release_Date: '15/03/19',
      duration: 12,
    },
    description:
      'After seeing a brutal murder, a woman flees from the killer through the streets of a surreal city.',
    icons: ['ouroboros', 'kinky_mask', 'eye'],
    backgroundImg: 'The_Witness_2',
    rating: 7.8,
  },
  {
    title: 'Suits',
    season: '1',
    episodeNumber: 4,
    secondaryDetails: {
      directed_By: 'Franck Balson',
      adapted_Script_By: 'Philip Gelatt',
      based_On_The_Story_By: 'Steven Lewis',
      animation_Studio: 'Blur Studio',
      release_Date: '15/03/19',
      duration: 17,
    },
    description:
      'A community of farmers use their homemade mechs to defend their families from an alien invasion.',
    icons: ['mug', 'barn', 'cows_head'],
    backgroundImg: 'Suits',
    rating: 7.5,
  },
  {
    title: 'Sucker of Souls',
    season: '1',
    episodeNumber: 5,
    secondaryDetails: {
      directed_By: 'Owen Sullivan',
      adapted_Script_By: 'Philip Gelatt',
      based_On_The_Story_By: 'Kirsten Cross',
      animation_Studio: 'Studio La Cachette',
      release_Date: '15/03/19',
      duration: 13,
    },
    description:
      'Unleashed by an archaeological dig, a bloodthirsty demon battles a team of mercenaries armed with... cats?',
    icons: ['cat', 'x_2', 'split_skull'],
    backgroundImg: 'Sucker_Of_Souls',
    rating: 6.5,
  },
  {
    title: 'When the Yoghurt Took Over',
    season: '1',
    episodeNumber: 6,
    secondaryDetails: {
      directed_By: 'Victor Maldonado & Alfredo Torres',
      adapted_Script_By: 'Janis Robertson',
      based_On_The_Story_By: 'John Scalzi',
      animation_Studio: 'Blow Studio',
      release_Date: '15/03/19',
      duration: 6,
    },
    description:
      'After scientists accidentally breed super-intelligent yogurt, it soon hungers for world domination.',
    icons: ['microscopic_beings', 'yogurt', 'strawberry'],
    backgroundImg: 'When_The_Yoghurt_Took_Over',
    rating: 6.9,
  },
  {
    title: 'Beyond the Aquila Rift',
    season: '1',
    episodeNumber: 7,
    secondaryDetails: {
      directed_By: 'Léon Bérelle, Dominique Boidin, Rémi Kozyra, Maxime Luère	',
      adapted_Script_By: 'Philip Gelatt',
      based_On_The_Story_By: 'Alastair Reynolds',
      animation_Studio: 'Unit Image	',
      release_Date: '15/03/19',
      duration: 17,
    },
    description:
      "Awakening after traveling light years off course, a ship's crew struggles to discover just how far they've come.",
    icons: ['penis', 'surge_tank', 'horrified_face'],
    backgroundImg: 'Beyond_The_Aquila_Rift',
    rating: 8.6,
  },
  {
    title: 'Good Hunting',
    season: '1',
    episodeNumber: 8,
    secondaryDetails: {
      directed_By: 'Oliver Thomas',
      adapted_Script_By: 'Philip Gelatt',
      based_On_The_Story_By: 'Ken Liu',
      animation_Studio: 'Red Dog Culture House',
      release_Date: '15/03/19',
      duration: 17,
    },
    description:
      'The son of a spirit hunter forges a bond with a shape-shifting huli jing.',
    icons: ['heart', 'cog', 'huli_jing_head'],
    backgroundImg: 'Good_Hunting',
    rating: 8.1,
  },
  {
    title: 'The Dump',
    season: '1',
    episodeNumber: 9,
    secondaryDetails: {
      directed_By: 'Javier Recio Gracia',
      adapted_Script_By: 'Philip Gelatt',
      based_On_The_Story_By: 'Joe Lansdale',
      animation_Studio: 'Able & Baker',
      release_Date: '15/03/19',
      duration: 10,
    },
    description:
      "Ugly Dave calls the garbage dump home, and he's not about to let some city slicker take it away from him.",
    icons: ['zippo', 'x_2', 'otto'],
    backgroundImg: 'The_Dump',
    rating: 6.3,
  },
  {
    title: 'Shape-Shifters',
    season: '1',
    episodeNumber: 10,
    secondaryDetails: {
      directed_By: 'Gabriele Pennacchioli',
      adapted_Script_By: 'Philip Gelatt',
      based_On_The_Story_By: 'Marko Kloos',
      animation_Studio: 'Blur Studio',
      release_Date: '15/03/19',
      duration: 16,
    },
    description:
      'Deep in Afghanistan, two Marines with supernatural powers face a threat from one of their own kind.',
    icons: ['dog_tags', 'x_2', 'moon'],
    backgroundImg: 'Shape_Shifters',
    rating: 7.5,
  },
  {
    title: 'Helping Hand',
    season: '1',
    episodeNumber: 11,
    secondaryDetails: {
      directed_By: 'Jon Yeo',
      adapted_Script_By: 'Philip Gelatt',
      based_On_The_Story_By: 'Claudine Griggs',
      animation_Studio: 'Axis Studios',
      release_Date: '15/03/19',
      duration: 10,
    },
    description:
      'Stranded in orbit, an astronaut must choose between life and limb before her oxygen runs out.',
    icons: ['heart', 'skull_2', 'car_freshener'],
    backgroundImg: 'Helping_Hand_2',
    rating: 7.4,
  },
  {
    title: 'Fish Night',
    season: '1',
    episodeNumber: 12,
    secondaryDetails: {
      directed_By: 'Damian Nenow',
      adapted_Script_By: 'Philip Gelatt',
      based_On_The_Story_By: 'Joe Lansdale',
      animation_Studio: 'Platige Image Studio',
      release_Date: '15/03/19',
      duration: 10,
    },
    description:
      'After their car breaks down in the desert, two salesmen take a dreamlike voyage to the dawn of time.',
    icons: ['night', 'road_sign', 'hook'],
    backgroundImg: 'Fish_Night',
    rating: 6.4,
  },
  {
    title: 'Lucky13',
    season: '1',
    episodeNumber: 13,
    secondaryDetails: {
      directed_By: 'Jerome Chen',
      adapted_Script_By: 'Philip Gelatt',
      based_On_The_Story_By: 'Mark Kloos',
      animation_Studio: 'Sony Pictures Imageworks',
      release_Date: '15/03/19',
      duration: 13,
    },
    description:
      "After the drop-ship Lucky 13 lost two crews, no pilot would fly her... but rookies don't get a choice.",
    icons: ['human_heart', 'x_2', 'horseshoe'],
    backgroundImg: 'Lucky_13',
    rating: 7.5,
  },
  {
    title: 'Zima Blue',
    season: '1',
    episodeNumber: 14,
    secondaryDetails: {
      directed_By: 'Robert Valley',
      adapted_Script_By: 'Philip Gelatt',
      based_On_The_Story_By: 'Alastair Reynolds',
      animation_Studio: 'Passion Animation Studios',
      release_Date: '15/03/19',
      duration: 10,
    },
    description:
      'The renowned artist Zima recounts his mysterious past and rise to fame before unveiling his final work.',
    icons: ['square', 'square', 'square'],
    backgroundImg: 'Zima_Blue',
    rating: 8.4,
  },
  {
    title: 'Blind Spot',
    season: '1',
    episodeNumber: 15,
    secondaryDetails: {
      directed_By: 'Vitaliy Shushko',
      adapted_Script_By: 'Vitaliy Shushko',
      based_On_The_Story_By: 'N/A',
      animation_Studio: 'Independent Studio / Elena Volk',
      release_Date: '15/03/19',
      duration: 8,
    },
    description:
      'A gang of cyborg thieves stage a high-speed heist of a heavily armored convoy.',
    icons: ['imp', 'skull_and_crossbones', 'thumbs_up'],
    backgroundImg: 'Blind_Spot',
    rating: 6.4,
  },
  {
    title: 'Ice Age',
    season: '1',
    episodeNumber: 16,
    secondaryDetails: {
      directed_By: 'Tim Miller',
      adapted_Script_By: 'Philip Gelatt',
      based_On_The_Story_By: 'Michael Swanswick',
      animation_Studio: 'Digic Pictures / Blur Studio / Atomic Fiction',
      release_Date: '15/03/19',
      duration: 10,
    },
    description:
      'A young couple moves into an apartment and finds a lost civilization inside their antique freezer.',
    icons: ['plug_socket', 'ice_cube', 'mushroom_cloud'],
    backgroundImg: 'Ice_Age',
    rating: 7.0,
  },
  {
    title: 'Alternate Histories',
    season: '1',
    episodeNumber: 17,
    secondaryDetails: {
      directed_By: 'Victor Maldonado & Alfredo Torres',
      adapted_Script_By: 'Philip Gelatt',
      based_On_The_Story_By: 'John Scalzi',
      animation_Studio: 'Sun Creature Studio',
      release_Date: '15/03/19',
      duration: 7,
    },
    description:
      'Want to see Hitler die in a variety of comically fantastic ways? Now you can. Welcome to Multiversity!',
    icons: ['x_2', 'x_2', 'clock'],
    backgroundImg: 'Alternate_Histories',
    rating: 6.4,
  },
  {
    title: 'The Secret War',
    season: '1',
    episodeNumber: 18,
    secondaryDetails: {
      directed_By: 'István Zorkóczy',
      adapted_Script_By: 'Philip Gelatt',
      based_On_The_Story_By: 'David W. Amendola',
      animation_Studio: 'Digic Pictures',
      release_Date: '15/03/19',
      duration: 10,
    },
    description:
      'Elite units of the Red Army fight an unholy evil deep in the ancient forests of Siberia.',
    icons: ['skull_2', 'skull_2', 'star'],
    backgroundImg: 'The_Secret_War',
    rating: 8.2,
  },
];
