export const episodeData = [
  {
    title: "Sonnie's Edge",
    season: '1',
    episodeNumber: '1',
    secondaryDetails: {
      directedBy: 'Dave Wilson',
      adaptedScriptBy: 'Philip Gelatt',
      basedOnTheStoryBy: 'Peter F. Hamilton',
      animationStudio: 'Blur Studio',
      releaseDate: '15/03/19',
      duration: '17 mins',
    },
    description:
      "In the underground world of 'beastie' fights, Sonnie is unbeatable -- as long as she keeps her edge.",
    icons: ['heart', 'x_2', 'snake'],
    backgroundImg: 'Sonnies_Edge',
    rating: 8.3,
  },
  {
    title: 'Three Robots',
    season: '1',
    episodeNumber: '2',
    secondaryDetails: {
      directedBy: 'Victor Maldonado & Alfredo Torres',
      adaptedScriptBy: 'Philip Gelatt',
      basedOnTheStoryBy: 'John Scalzi',
      animationStudio: 'Blow Studio',
      releaseDate: '15/03/19',
      duration: '12 mins',
    },
    description:
      'Long after the fall of humanity, three robots embark on a sightseeing tour of a post-apocalyptic city.',
    icons: ['one_eyed_robot', 'apocalypse_tourist', 'slime_burger'],
    backgroundImg: 'Three_Robots',
    rating: 8.0,
  },
  {
    title: 'The Witness',
    season: '1',
    episodeNumber: '3',
    secondaryDetails: {
      directedBy: 'Alberto Mielgo',
      adaptedScriptBy: 'ALbert Mielgo',
      basedOnTheStoryBy: 'N/A',
      animationStudio: 'Pinkman TV',
      releaseDate: '15/03/19',
      duration: '12 mins',
    },
    description:
      'After seeing a brutal murder, a woman flees from the killer through the streets of a surreal city.',
    icons: ['snake_eat_self', 'sadomazofembotochist', 'eye'],
    backgroundImg: 'The_Witness_2',
    rating: 7.8,
  },
  {
    title: 'Suits',
    season: '1',
    episodeNumber: '4',
    secondaryDetails: {
      directedBy: 'Franck Balson',
      adaptedScriptBy: 'Philip Gelatt',
      basedOnTheStoryBy: 'Steven Lewis',
      animationStudio: 'Blur Studio',
      releaseDate: '15/03/19',
      duration: '17 mins',
    },
    description:
      'A community of farmers use their homemade mechs to defend their families from an alien invasion.',
    icons: ['blood_like', 'barn', 'apocalypse_tourist'],
    backgroundImg: 'Suits',
    rating: 7.5,
  },
  {
    title: 'Sucker of Souls',
    season: '1',
    episodeNumber: '5',
    secondaryDetails: {
      directedBy: 'Owen Sullivan',
      adaptedScriptBy: 'Philip Gelatt',
      basedOnTheStoryBy: 'Kirsten Cross',
      animationStudio: 'Studio La Cachette',
      releaseDate: '15/03/19',
      duration: '13 mins',
    },
    description:
      'Unleashed by an archaeological dig, a bloodthirsty demon battles a team of mercenaries armed with... cats?',
    icons: ['blood_like', 'barn', 'apocalypse_tourist'],
    backgroundImg: 'Sucker_Of_Souls',
    rating: 6.5,
  },
  {
    title: 'When the Yoghurt Took Over',
    season: '1',
    episodeNumber: '6',
    secondaryDetails: {
      directedBy: 'Victor Maldonado & Alfredo Torres',
      adaptedScriptBy: 'Janis Robertson',
      basedOnTheStoryBy: 'John Scalzi',
      animationStudio: 'Blow Studio',
      releaseDate: '15/03/19',
      duration: '6 mins',
    },
    description:
      'After scientists accidentally breed super-intelligent yogurt, it soon hungers for world domination.',
    icons: ['blood_like', 'barn', 'apocalypse_tourist'],
    backgroundImg: 'When_The_Yoghurt_Took_Over',
    rating: 6.9,
  },
  {
    title: 'Beyond the Aquila Rift',
    season: '1',
    episodeNumber: '7',
    secondaryDetails: {
      directedBy: 'Léon Bérelle, Dominique Boidin, Rémi Kozyra, Maxime Luère	',
      adaptedScriptBy: 'Philip Gelatt	',
      basedOnTheStoryBy: 'Alastair Reynolds',
      animationStudio: 'Unit Image	',
      releaseDate: '15/03/19',
      duration: '17 mins',
    },
    description:
      "Awakening after traveling light years off course, a ship's crew struggles to discover just how far they've come.",
    icons: ['blood_like', 'barn', 'apocalypse_tourist'],
    backgroundImg: 'Beyond_The_Aquila_Rift',
    rating: 6.5,
  },
];
